services:
  - type: web
    name: sssl-har-backend
    env: python
    region: ohio
    plan: free # Can upgrade to starter for $7/mo to prevent sleeping
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "uvicorn backend.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
